<a href="https://colab.research.google.com/github/rajdeep-2004/ml_midsems/blob/main/EncodingCatergoricalData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ordinal Encoding

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('customer.csv')

In [ ]:
df.sample(5)

    age  gender   review education purchased
33   89  Female     Good        PG       Yes
24   16  Female  Average        PG       Yes
48   39  Female     Good        UG       Yes
34   86    Male  Average    School        No
22   18  Female     Poor        PG       Yes

In [ ]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [ ]:
df = df.iloc[:, [2, 3, 4]]

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop('purchased', axis=1),
                                                    df['purchased'],
                                                    test_size = 0.3,
                                                    random_state = 0)
X_train.shape, X_test.shape

((35, 2), (15, 2))

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

o_encoder = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])
# the list is in increasing order of importance , Poor = 0, Average = 1 and so on

o_encoder.fit(X_train)

X_train_o_encoded = o_encoder.transform(X_train)
X_test_o_encoded = o_encoder.transform(X_test)

In [ ]:
from sklearn.preprocessing import LabelEncoder

l_encoder = LabelEncoder()

l_encoder.fit(y_train)

y_train_l_encoded = l_encoder.transform(y_train)
y_test_l_encoded = l_encoder.transform(y_test)